[package]
name = "wrestlers-adapter"
version = "0.3.2"
authors = ["Bunts Thy Unholy <bunts@hhd.com.au>"]

[dependencies]
regex = "0.1"
lazy_static = "0.1.*"
hyper = "0.9"
daemonize = "0.2.*"
log = "0.3.*"
env_logger = "0.3.*"
